In [27]:
import torch
import torch.nn as nn

In [2]:
class Test(torch.nn.Module):
    def __init__(self):
        super(Test,self).__init__()
        self.linear1 = torch.nn.Linear(2,3)
        self.linear2 = torch.nn.Linear(3,4)
        self.bn = torch.nn.BatchNorm2d(4)
        


In [3]:
test_modeule = Test()

In [6]:
test_modeule._modules

OrderedDict([('linear1', Linear(in_features=2, out_features=3, bias=True)),
             ('linear2', Linear(in_features=3, out_features=4, bias=True)),
             ('bn',
              BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True))])

In [9]:
test_modeule._modules['linear1'].weight.dtype

torch.float32

In [12]:
test_modeule.to(torch.float16)
test_modeule._modules['linear1'].weight#.dtype

Parameter containing:
tensor([[-0.1196,  0.5415],
        [-0.3845,  0.0394],
        [-0.2261, -0.5688]], dtype=torch.float16, requires_grad=True)

In [14]:
test_modeule.state_dict()

OrderedDict([('linear1.weight',
              tensor([[-0.1196,  0.5415],
                      [-0.3845,  0.0394],
                      [-0.2261, -0.5688]], dtype=torch.float16)),
             ('linear1.bias',
              tensor([-0.3662,  0.4841,  0.4192], dtype=torch.float16)),
             ('linear2.weight',
              tensor([[-0.1236,  0.2952, -0.2917],
                      [-0.2140, -0.1775, -0.0979],
                      [-0.4617, -0.1840,  0.0292],
                      [-0.2832, -0.5200,  0.3079]], dtype=torch.float16)),
             ('linear2.bias',
              tensor([-0.1020, -0.2490,  0.3291,  0.0096], dtype=torch.float16)),
             ('bn.weight', tensor([1., 1., 1., 1.], dtype=torch.float16)),
             ('bn.bias', tensor([0., 0., 0., 0.], dtype=torch.float16)),
             ('bn.running_mean',
              tensor([0., 0., 0., 0.], dtype=torch.float16)),
             ('bn.running_var', tensor([1., 1., 1., 1.], dtype=torch.float16)),
             ('bn.nu

In [15]:
test_modeule.state_dict()['linear1.weight']

tensor([[-0.1196,  0.5415],
        [-0.3845,  0.0394],
        [-0.2261, -0.5688]], dtype=torch.float16)

In [26]:

for p in test_modeule.named_parameters():
    print(p)
    break

('linear1.weight', Parameter containing:
tensor([[-0.1196,  0.5415],
        [-0.3845,  0.0394],
        [-0.2261, -0.5688]], dtype=torch.float16, requires_grad=True))


# 参数初始化

In [32]:
@torch.no_grad()
def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.fill_(1.0)
        print(m.weight)
net = nn.Sequential(nn.Linear(2,2), nn.Linear(2,2))
net.apply(init_weights)

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [38]:
net.__dict__

{'training': True,
 '_parameters': OrderedDict(),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': OrderedDict(),
 '_modules': OrderedDict([('0',
               Linear(in_features=2, out_features=2, bias=True)),
              ('1', Linear(in_features=2, out_features=2, bias=True))])}